#!/bin/sh

if test $# -ne 1 && test $# -ne 2
then
    cat <<EOF >&2
usage: ${0} KEY [DEFAULT]

Read KEY from Qubes DB and interpret it as boolean value. Non-empty string is
considered true and both empty string and no value at are considered false. The
value is reported as exit code, 0 for true, 1 for empty string, DEFAULT
(if not specified, 2) for not found, and 3 for an error.
EOF
    exit 3
fi

KEY="$1"
DEFAULT="${2:-2}"

result=$(qubesdb-read "$KEY" 2>/dev/null)
status=$?

case $status in
(0) if test -n "$result"; then exit 0; else exit 1; fi;;
(2) exit "$DEFAULT";;
(*) exit 3;;
esac
